//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyRapphim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BooId { get; set; }
        public Nullable<int> CusId { get; set; }
        public Nullable<int> ShoId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Bilmoney { get; set; }
        public Nullable<System.DateTime> DateBooking { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ShowTime ShowTime { get; set; }
    }
}
