//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyRapphim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeeId { get; set; }
        public Nullable<int> FilId { get; set; }
        public string Avata { get; set; }
        public string FullName { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
