//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyRapphim
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShowTime()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ShoId { get; set; }
        public Nullable<int> FilId { get; set; }
        public Nullable<int> CinId { get; set; }
        public System.DateTime ShowTime1 { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> View { get; set; }
        public double Price { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Cinema Cinema { get; set; }
        public virtual Film Film { get; set; }
    }
}
